sudo: false

language: go

before_script:
  - go get -u golang.org/x/tools/cmd/vet
  - go get -u github.com/golang/lint/golint

go: 1.5
script:
  - test -z "$(gofmt -s -l -w . | tee /dev/stderr)"
  - test -z "$(golint . |  tee /dev/stderr)"
  - go vet .
  - go build -v .
  - go test -v .
